- name: RESET CLUSTER BOIII
  hosts: all_server
  gather_facts: False
  become: true
  tasks:
    - name: reset cluster
      command: kubeadm reset -f
      register: result
    - debug:
        var: result
    - name: delete ovn cni
      shell: |
        rm -rf /var/run/openvswitch
        rm -rf /var/run/ovn
        rm -rf /etc/origin/openvswitch/
        rm -rf /etc/origin/ovn/
        rm -rf /etc/cni/net.d/00-kube-ovn.conflist
        rm -rf /etc/cni/net.d/01-kube-ovn.conflist
        rm -rf /var/log/openvswitch
        rm -rf /var/log/ovn
        rm -fr /var/log/kube-ovn
    - name: restart node
      reboot:
        reboot_timeout: 300
