apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
  namespace: example
data:
  nginx.conf:
    |-
      worker_processes 4;

      events { worker_connections 1024; }

      http {
          server {
              listen 8080;
              root  /var/www/html/web;
              include /etc/nginx/mime.types;
              
              add_header X-Frame-Options "DENY";
              add_header X-XSS-Protection "1; mode=block";
              add_header X-Robots-Tag none;
              server_tokens off;
              location / {
                  try_files $uri /index.html;
              }
          }
      }
