apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web
  namespace: example
spec:
  maxReplicas: 5
  minReplicas: 2
  behavior:
  scaleDown:
    stabilizationWindowSeconds: 60 #defualt 5 min
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
  metrics:
   - type: Resource
     resource:
       name: cpu
       target:
         type: Utilization
         averageUtilization: 50
   - type: Resource
     resource:
       name: memory
       target:
         type: Utilization
         averageUtilization: 70
